services:
  judge0-db:
    image: postgres:13-alpine
    env_file: judge0.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: unless-stopped

  judge0-redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    restart: unless-stopped

  judge0-server:
    image: judge0/judge0:latest
    volumes:
      - ./judge0-data:/judge0-data
    ports:
      - "2358:2358"
    privileged: true
    env_file: judge0.conf
    environment:
      - ENABLE_WAIT_RESULT=true
      - ENABLE_COMPILER_OPTIONS=true
      - DISABLE_SANDBOX=true
    depends_on:
      - judge0-db
      - judge0-redis
    restart: unless-stopped

  judge0-worker:
    image: judge0/judge0:latest
    command: ["./scripts/workers"]
    volumes:
      - ./judge0-data:/judge0-data
    privileged: true
    env_file: judge0.conf
    environment:
      - ENABLE_WAIT_RESULT=true
      - ENABLE_COMPILER_OPTIONS=true
      - DISABLE_SANDBOX=true
    depends_on:
      - judge0-db
      - judge0-redis
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:
